# Generated by Django 4.1 on 2024-05-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('token', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('battery_health', models.IntegerField(default=0)),
                ('screen_health', models.IntegerField(default=0)),
                ('camera_health', models.IntegerField(default=0)),
                ('body_health', models.IntegerField(default=0)),
                ('performance_health', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_check.post')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_check.technician')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_check.user'),
        ),
    ]
