# Generated by Django 4.1 on 2024-05-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='post_token',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='technician_id',
            new_name='technician',
        ),
    ]
