# Generated by Django 4.1 on 2024-05-15 12:16

from django.db import migrations, models
import django.db.models.deletion

from user_management.models import Post


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_user_access_token'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='post',
            field=models.ForeignKey(default=Post.objects.get(token="gZEhY4g7"), on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='user_management.post'),
            preserve_default=False,
        ),
    ]
