# Generated by Django 4.1 on 2024-05-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='access_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
