"""
Django settings for kenar_example project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ptdgn^0%lglx$h40i7d%bny0p=*im6lb3+(iu5_=@r^@c8kvwv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["kenar-example.darkube.app", "localhost", "4a87a4ffc92991290d80f2225fefbe93.serveo.net", "4f54-16-24-70-196.ngrok-free.app"]

CSRF_TRUSTED_ORIGINS = ['https://kenar-example.darkube.app', 'http://localhost:8000', 'http://127.0.0.1:8000']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls',
    'user_management',
    'tech_check',
    'chat'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kenar_example.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'polls/templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kenar_example.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.postgresql_psycopg2',

        'NAME': 'kenar',

        'USER': 'postgres',

        'PASSWORD': 'm60iT3NcTrjlk0Cowu38FgX9Zjk5Z3jj',

        'HOST': '1ea30ff6-380f-4b23-b2af-dcd3b160b530.hsvc.ir',

        'PORT': '31955',

    }

}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DIVAR_APP_SLUG = "mire-sulpher-elf"
DIVAL_OAUTH_REDIRECT_URL = "https://open-platform-redirect.divar.ir/oauth"
DIVAR_FALLBACK_REDIRECT_URL = "https://kenar-example.darkube.app/oauth/callback"
DIVAR_API_KEY = ("45kFWH2rsoQKBeZRWTYb5pleDGn16KS8dNLaM3cXWC63XESkeQYiOJaAC8vpxJkB"
                 "xaQJ2UQ9Ce2YOV6WwLiI313xpPqYWSvtcF6JPGHW9DzwnrTI1ZBrIT4f0Ip9HPqup"
                 "5HfQmyCqQMslCFl2kVBysSZYXFdtDbWEGtU0R47V8KdwFUwFaKh3TtASNQ4MKvMsod"
                 "Sf6iyJqvqhTRl7DUOmRS62JaNLVg142EfBcNFJ0Ypl2HhOhLnW6pQn8U8pyiq")
DIVAR_OAUTH_ACCESS_TOKEN_URL = "https://api.divar.ir/v1/open-platform/oauth/access_token"
DIVAR_OPEN_PLATFORM_BASE_URL = "https://api.divar.ir/v1/open-platform"
